mystr = "hari is good boy"
print(len(mystr))
print(mystr[0:6])
print(mystr[0:16])
print(mystr[0:78])
print(mystr[0:])
print(mystr[:6])
print(mystr[:])
print(mystr[0:16:2])
print(mystr[::2])
print(mystr[::])
print(mystr[-4:-2])
print(mystr[::-1])
print(mystr[::-2])

print(mystr.isalnum())
print(mystr.isalpha())
print(mystr.endswith("boy"))
print(mystr.count("b"))
print(mystr.capitalize())
print(mystr.upper())
print(mystr.lower())
print(mystr.find("is"))
print(mystr.replace("is", "are"))